version: '3.8'

services:
  # --- 1. PostgreSQL Database with pgvector ---
  db:
    image: ankane/pgvector:latest
    container_name: gemma3_db
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5

  # --- 2. Ollama GPU Service ---
  ollama:
    build:
      context: ./ollama
    container_name: gemma3_ollama
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ports:
      - "11434:11434"
    volumes:
      - ollama_models:/root/.ollama
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:11434"]
      interval: 30s
      timeout: 10s
      retries: 5

  # --- 3. FastAPI Main App ---
  api:
    build: .
    container_name: gemma3_api
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      ollama:
        condition: service_healthy
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8000/docs"]
      interval: 30s
      timeout: 10s
      retries: 5

  # --- 4. Open WebUI (User Interface) ---
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - open-webui-data:/app/backend/data
    depends_on:
      ollama:
        condition: service_healthy
    environment:
      - OLLAMA_HOST=http://ollama:11434

  # --- 5. Scraper Agent ---
  scraper:
    build:
      context: .
      dockerfile: agents/scraper/Dockerfile
    container_name: gemma3_scraper
    restart: on-failure
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      ollama:
        condition: service_healthy
      api:
        condition: service_healthy
    command: ["python", "scraper.py"]

volumes:
  db_data:
  ollama_models:
  open-webui-data:
